### ISSUE TITLE
Blogeinträge: in Detailseite fehlt der Text des Blog-Eintrages

### ISSUE THREAD

**Issue by dpomt** [DigitalerSchulhof/Website#3]
Vorweg: klasse Plattform. Vielen Dank für Ihre super Arbeit.

In Detailseite fehlt der Text des Blog-Eintrages.
Das ist insofern ungeschickt, als dass Links im Text in der Blog-Seite nur schwer per Copy&Paste kopierbar sind.

**Comment by dpomt** [comment]
![blog2](https://user-images.githubusercontent.com/1379660/80206058-fcba3980-862b-11ea-8d45-ab7d51510ae1.JPG)
![blog1](https://user-images.githubusercontent.com/1379660/80206062-fd52d000-862b-11ea-912e-3d7a5989929c.JPG)

**Comment by jeengbe** [comment]
In die Ansicht übernommen.

**Comment by dpomt** [comment]
Ist nur in dev übernommen, noch nicht auf bg.schorndorf.de, oder?

**Comment by jeengbe** [comment]
Ja

**Comment by jeengbe** [comment]
Zugangscode im Bild
