### ISSUE TITLE
Blog-Einträge: Links analog zu Dateien einbinden

### ISSUE THREAD

**Issue by dpomt** [DigitalerSchulhof/Website#4]
es wäre praktisch, wenn Links so eingestellt werden könnten, dass Sie separat aufgelistet werden (und anklickbar sind). 
Analog zu Dateien in Blog-Eintrag-Details "Zugehörige Downloads"
![image](https://user-images.githubusercontent.com/1379660/80206033-f0ce7780-862b-11ea-85cc-7c373d51ef39.png)

**Comment by jeengbe** [comment]
![Erster Sketch](https://user-images.githubusercontent.com/51749023/80208316-3bea8980-8630-11ea-8fa1-3b26f6447fa0.png)
Gar keine schlechte Idee

**Comment by dpomt** [comment]
danke
